# Generated by Django 4.2.23 on 2025-07-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYTSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=100)),
                ('where', models.CharField(max_length=200)),
                ('when', models.CharField(max_length=100)),
                ('what', models.CharField(max_length=200)),
                ('how', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='kyt_images/')),
                ('expected_injury', models.TextField()),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('countermeasures', models.TextField(blank=True)),
                ('final_goal', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
