# Generated by Django 4.2.23 on 2025-07-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0002_kytsession_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='kytsession',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
