# Generated by Django 4.2.23 on 2025-07-17 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0003_kytsession_risk_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kytsession',
            name='countermeasures',
        ),
        migrations.CreateModel(
            name='Countermeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='対策内容')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countermeasures', to='kytapp.kytsession')),
            ],
        ),
    ]
