# Generated by Django 4.2.23 on 2025-07-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0004_remove_kytsession_countermeasures_countermeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kytsession',
            name='what',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='kytsession',
            name='when',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kytsession',
            name='where',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='kytsession',
            name='who',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
