# Generated by Django 4.2.23 on 2025-10-20 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0005_alter_kytsession_what_alter_kytsession_when_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_name', models.CharField(max_length=100)),
                ('severity', models.IntegerField()),
                ('probability', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='kytapp.kytsession')),
            ],
        ),
    ]
