# Generated by Django 4.2.23 on 2025-10-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0006_riskevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kytsession',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='kytsession',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='kytsession',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='riskevaluation',
            name='evaluator_name',
        ),
        migrations.AlterField(
            model_name='kytsession',
            name='expected_injury',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kytsession',
            name='how',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='riskevaluation',
            name='probability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskevaluation',
            name='severity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
