# Generated by Django 4.2.23 on 2025-10-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0007_remove_kytsession_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskevaluation',
            name='evaluator_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
