# Generated by Django 4.2.23 on 2025-11-09 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0008_riskevaluation_evaluator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kytsession',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('who', models.CharField(blank=True, max_length=100)),
                ('where', models.CharField(blank=True, max_length=100)),
                ('when', models.CharField(blank=True, max_length=100)),
                ('what', models.CharField(blank=True, max_length=100)),
                ('how', models.TextField(blank=True)),
                ('expected_injury', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='kytapp.kytsession')),
            ],
        ),
    ]
