# Generated by Django 4.2.23 on 2025-11-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0009_kytsession_risk_score_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='expected_injury',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='how',
            field=models.TextField(blank=True, null=True),
        ),
    ]
