# Generated by Django 4.2.23 on 2025-11-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0010_alter_participant_expected_injury_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='what',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='when',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='where',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='who',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
