# Generated by Django 4.2.23 on 2025-11-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0011_alter_participant_what_alter_participant_when_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kytsession',
            name='expected_injury',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kytsession',
            name='final_goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kytsession',
            name='how',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kytsession',
            name='what',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kytsession',
            name='when',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kytsession',
            name='where',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kytsession',
            name='who',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
