# Generated by Django 4.2.23 on 2025-11-10 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0012_alter_kytsession_expected_injury_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskevaluation',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kytapp.participant'),
        ),
    ]
