# Generated by Django 4.2.23 on 2025-11-10 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0013_riskevaluation_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskevaluation',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kytapp.participant'),
        ),
    ]
