# Generated by Django 4.2.23 on 2025-11-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0014_alter_riskevaluation_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='kytsession',
            name='participant_count',
            field=models.IntegerField(default=1, verbose_name='参加者人数'),
        ),
    ]
