# Generated by Django 4.2.26 on 2025-12-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0015_kytsession_participant_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='color',
            field=models.CharField(default='#ccc', max_length=10),
        ),
    ]
