# Generated by Django 4.2.26 on 2025-12-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0016_participant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='countermeasure',
            name='what',
            field=models.CharField(blank=True, max_length=100, verbose_name='なにを'),
        ),
        migrations.AddField(
            model_name='countermeasure',
            name='when',
            field=models.CharField(blank=True, max_length=100, verbose_name='いつ'),
        ),
        migrations.AddField(
            model_name='countermeasure',
            name='where',
            field=models.CharField(blank=True, max_length=100, verbose_name='どこで'),
        ),
        migrations.AddField(
            model_name='countermeasure',
            name='who',
            field=models.CharField(blank=True, max_length=100, verbose_name='だれが'),
        ),
    ]
