# Generated by Django 4.2.26 on 2025-12-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0017_countermeasure_what_countermeasure_when_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countermeasure',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
    ]
