# Generated by Django 4.2.26 on 2025-12-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0018_countermeasure_is_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='kytsession',
            name='fixed_what_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kytsession',
            name='round1_mode',
            field=models.CharField(choices=[('random', 'すべてランダム'), ('fixed_what', 'whatを固定')], default='random', max_length=20),
        ),
    ]
