# Generated by Django 4.2.26 on 2025-12-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0019_kytsession_fixed_what_image_kytsession_round1_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='kytsession',
            name='fixed_what_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
