# Generated by Django 4.2.26 on 2025-12-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0020_kytsession_fixed_what_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='kytsession',
            name='round3_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
