# Generated by Django 4.2.26 on 2025-12-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kytapp', '0021_kytsession_round3_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='kytsession',
            name='round3_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
